### ISSUE TITLE
about channel aggregation

### ISSUE THREAD

**Issue by wsVIC** [thuml/TimesNet#23]
maybe silly question, but according to the paper, you mentioned in 3.1 after doing FFT and Amp, you did an avg between each channel, but this affair did't mentioned anywhere in the rest of the paper. Furthermore, in 3.2, you firstly did a projection from T*C to T*d_model, effectively aggregating each channel before they were processed. Won't this move hurt the frequency information of individual channel? This is quite confusing for me overall. Appreciate it if you can provide an answer

**Comment by wuhaixu2016** [comment]
Hi, very interesting question.

Firstly, we project the input (multivariate series) into the deep representations for a unified and comprehensive understanding of the input information. After this projection, all the channels are equivalent. Thus, I average along the channel dimension for the periodicity process.

About the question "Won't this move hurt the frequency information of individual channel?" I have to say that there is no free lunch for multivariate modeling. Since we want to accomplish multivariate forecasting within one model, we have to face the potential competition among different varieties. In TimesNet, we directly project multiple series into one unified representation for a better understanding of the overall semantic information.
