### ISSUE TITLE
Clarification on TimesBlock

### ISSUE THREAD

**Issue by linfeng-du** [thuml/TimesNet#4]
Thank you for your fantastic work!

Regarding the proposed TimesBlock, I would like to confirm if the reshape and convolution operations are carried out in the time domain. It's just that the frequencies and periods used to decide the shape is computed from the Fourier domain? Besides, is the number of chunks decided by partitioning the time series into chunks of length $p_i$ (after padding)?

The point of the question is that, if the partition is carried out in the time domain, then each chunk still contains all the frequencies that exist in the full series so we can't say that each Inception block only focus on modeling the "intra and inter period variation" of a single frequency right? Or can we say that, the "intra and inter period variation" is exactly caused by the accumulation effects of multiple frequencies?

Also, could you please explain a bit more on how to see the inter and intra period variation in the figure?
![image](https://github.com/thuml/TimesNet/assets/34938020/66ba487f-d13a-4261-8b5a-ad8949a91d65)

**Comment by wuhaixu2016** [comment]
Hi, thanks for your insightful question.

Yes, the reshape and convolution operations are in the time domain. And the number of chunks are decided by period length p_i (**before padding**).

Your point are right. All the chunks will contain full series. But since the 2D variation map is reshaped from one certain period length, it will highlight the feature from one certain period of time series.

It also notable that, it is meaningless if you only separate one certain period information, since the separated series will exactly be a smooth sin or cos function curve.
